/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Set Application Icon
 #	author : miyako
 #	2016/05/30
 #
 # --------------------------------------------------------------------------------*/

// --- Set Application Icon
void SET_APPLICATION_ICON(sLONG_PTR *pResult, PackagePtr pParams);

#if VERSIONWIN
#pragma pack(push, 2)
typedef	struct {
	unsigned short	reserved;		/* reserved, always 0	*/
	unsigned short	resourceType;	/* 1 = ico, 2 = cur */
	unsigned short	resourceCount;	/* number of images in this file */
}	IconFileHeader;

typedef	struct {
	unsigned char	width;			/* w */
	unsigned char	height;			/* h */
	unsigned char	color;			/* 0 = more than 256 colours */
	unsigned char	reserved;
	unsigned short	colorPlanes;	/* colour planes */
	unsigned short	bitsPerPixel;	/* bits per pixel */
	unsigned int	dataSize;		/* data size */
	unsigned int	offsetToImage;	/* offset to image */
}	IconInfoHeader;

typedef	struct {
	unsigned int	headerSize;		/* header size */
	unsigned int	width;			/* width, can be 0 */
	unsigned int	height;			/* height, can be 0 */
	unsigned short	planes;			/* number of planes, always 1 */
	unsigned short	bitsPerPixel;	/* bits per pixel, can be 0 */
	unsigned int	format;			/* 5 = png */
	unsigned int	size;			/* size, can be 0 */
	unsigned int	x;				/* x pixel per meter, can be 0 */
	unsigned int	y;				/* y pixel per meter, can be 0 */
	unsigned int	used;			/* used palettes, can be 0 */
	unsigned int	important;		/* important palettes, can be 0 */
}	BitmapInfoHeader;

typedef	struct {
	unsigned char	width;			/* w */
	unsigned char	height;			/* h */
	unsigned char	color;			/* 0 = more than 256 colours */
	unsigned char	reserved;
	unsigned short	colorPlanes;	/* colour planes */
	unsigned short	bitsPerPixel;	/* bits per pixel */
	unsigned int	dataSize;		/* data size */
	unsigned short	resourceID;		/* n */
}	IconGroupHeader;

typedef	struct {
	unsigned short	reserved;		/* reserved, always 0	*/
	unsigned short	resourceType;	/* 1 = ico, 2 = cur */
	unsigned short	resourceCount;	/* number of images in this file */
	IconGroupHeader resources[6];
}GroupIconHeader;
#pragma pack(pop)
#endif